name: SBOM Generator

on:
  push:
    branches:
      - main
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

permissions: read-all
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate SBOM
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0
        with:
          path: ./
          format: spdx-json
          output-file: flerapii-sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v6
        with:
          name: sbom
          path: flerapii-sbom.spdx.json
